#pragma once


enum
{
	HTTP_SWITCHING_PROTOCOLS = 101,
	HTTP_OK = 200,
	HTTP_FOUND = 302,
	HTTP_BAD_REQUEST = 400,
	HTTP_UNAUTHORIZED = 401,
	HTTP_FORBIDDEN = 403,
	HTTP_NOT_FOUND = 404,
	HTTP_PAYLOAD_TOO_LARGE = 413,
	HTTP_URI_TOO_LONG = 414,
	HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
	HTTP_INTERNAL_SERVER_ERROR = 500,
	HTTP_METHOD_NOT_IMPLEMENTED = 501,
};



